# Generated by Django 3.1.4 on 2020-12-24 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20201222_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['rating', '-published']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published']},
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
    ]
